### ISSUE TITLE
Slow performance on Nomad API documentation pages

### ISSUE THREAD

**Issue by endocrimes** [hashicorp/dev-portal#1401]
👋,

Since the move to `developer.hashicorp.com` I've been running into a few performance issues compared to the old Nomad documentation (both time to render a page and ongoing memory usage, with things like the nomad jobs api page taking ~500-800MB of RAM alone).

For a specific example: https://developer.hashicorp.com/nomad/api-docs/jobs takes about 3 minutes to render on my 32 core / 64GB RAM desktop in Firefox 107. It also appears that this needs to recompute on every page load.

I'm not really a competent browser person, but I can upload a Firefox profile if that's helpful 😅

**Comment by BRKalow** [comment]
Thanks so much for the report! We're investigating this and will report back when we've found a fix.
